### ISSUE TITLE
1.20.1 compatibility

### ISSUE THREAD

**Issue by ItsProfessional** [Awakened-Redstone/OptionsReload#8]
### Is your feature request related to a problem? Please describe.

It isn't

### Describe the solution you'd like

1.20.1 compatibility

### Describe alternatives you've considered

not relevant here

**Comment by ItsProfessional** [comment]
can you upload the new build on modrinth?

**Comment by Awakened-Redstone** [comment]
Uploaded it, sorry, was a bit busy
I also updated the code a bit
